version: "3.9"
services:
  react-app:
    build:
      context: ./react-app
    ports:
      - 4000:4000
    volumes:
      - ./react-app/src:/app/src
  flask-app:
    build: ./flask-app
    ports:
      - "8000:5000"
    environment:
      - FLASK_DEBUG:"true"
    depends_on:
      - react-app
  redis:
    image: "redis:alpine"
    
  relay:
    image: "getsentry/relay"
    volumes:
      - ./config/:/work/.relay/:z
